### ISSUE TITLE
PETS 2009 link error

### ISSUE THREAD

**Issue by ciwei123** [SpyderXu/multi-object-tracking-paper-list#6]
@SpyderXu Hi,thanks for your sharing ,I want to download the PETS 2009 dataset, but the link is error. What should I do? Could you provided the groundtruth of PETS 2009 S2 for me? Thank you very much!!!

**Comment by zardilior** [comment]
PETS 2009 S2 can be found lower in the website linked. THere is also a ftp link. Tried the first one and it had problems. This link over here works nice http://cs.binghamton.edu/~mrldata/pets2009.html . I only googled it and tried it. Hope it helps

**Comment by zardilior** [comment]
@SpyderXu mark as closed if you could

**Comment by Coronal-Halo** [comment]
@zardilior That link also does not work anymore.
